In [ ]:
Q1

In [7]:
#Yes, there is a difference in the data type of the list_ variable and the array_list variable. The list_ variable is a Python list, whereas the array_list variable is a NumPy array.
import numpy as np
list_=['1','2','3','4','5']
array_list=np.array(object=list_)

for i in array_list:
    print("array list:",type(i))
for j in list_:
    print("list:",type(j))


array list: <class 'numpy.str_'>
array list: <class 'numpy.str_'>
array list: <class 'numpy.str_'>
array list: <class 'numpy.str_'>
array list: <class 'numpy.str_'>
list: <class 'str'>
list: <class 'str'>
list: <class 'str'>
list: <class 'str'>
list: <class 'str'>


In [ ]:
Q2

In [8]:
import numpy as np
list=['1','2','3','4','5']
array_list=np.array(object=list)

for i in array_list:
    print("array list:",type(i))
for j in list:
    print("list:",type(j))


array list: <class 'numpy.str_'>
array list: <class 'numpy.str_'>
array list: <class 'numpy.str_'>
array list: <class 'numpy.str_'>
array list: <class 'numpy.str_'>
list: <class 'str'>
list: <class 'str'>
list: <class 'str'>
list: <class 'str'>
list: <class 'str'>


In [ ]:
Q3

In [13]:
#Yes, there will be a difference in the data type of the elements present in the list_ variable and the array_list variable when you explicitly specify the dtype as int while creating the NumPy array array_list.
import numpy as np
list_=['1','2','3','4','5']
array_list = np.array(object = list_, dtype = int)
print(array_list)
for i in array_list:
    print("array list:",type(i))
for j in list_:
    print("list:",type(j))


[1 2 3 4 5]
array list: <class 'numpy.int32'>
array list: <class 'numpy.int32'>
array list: <class 'numpy.int32'>
array list: <class 'numpy.int32'>
array list: <class 'numpy.int32'>
list: <class 'str'>
list: <class 'str'>
list: <class 'str'>
list: <class 'str'>
list: <class 'str'>


In [ ]:
Q4

In [19]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
shape=num_array.shape
print(shape)
size=num_array.size
print(size)

(2, 3)
6


In [ ]:
Q5

In [20]:
import numpy as np
zeros_matrix = np.zeros((3, 3))
print(zeros_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6

In [22]:
import numpy as np
identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
